from .Assignment import *
from .AssignmentStudent import *
from .AssignmentGroup import *
from .Courses import *
from .EvaluationAssignment import *
from .Groups import *
from .GroupStudent import *
from .GroupTeacher import *
from .IndicatorMeasure import *
from .IndicatorAssignment import *
from .IndicatorGroup import *
from .Login import *
from .PerformanceIndicator import *
from .Rubric import *
from .StudentOutcome import *
from .UploadStudents import *
from .UploadRubrics import *
from .UpdateStudents import *
from .CreateStudents import *
from .Program import *
