# Generated by Django 3.2.5 on 2021-07-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('idPerson', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('charge', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('idAssignment', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nameAssignament', models.CharField(max_length=60)),
                ('dateAssignment', models.DateTimeField()),
                ('dateLimitAssignment', models.DateTimeField()),
                ('description', models.CharField(max_length=60)),
                ('format', models.CharField(max_length=60)),
                ('delivery', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentAttached', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('codeCourse', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('referencePlan', models.IntegerField(default=1)),
                ('nameCourse', models.CharField(default='Test', max_length=60)),
                ('departmentCourse', models.CharField(default=1, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EducationResult',
            fields=[
                ('codeResult', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCo',
            fields=[
                ('numGroup', models.BigIntegerField(primary_key=True, serialize=False)),
                ('periodPlan', models.CharField(default='Test', max_length=60)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course')),
            ],
        ),
        migrations.CreateModel(
            name='PairEvaluator',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('idPerson', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('institution', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('codeRubric', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rubric', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('idPerson', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('carrer', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('idPerson', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('departmentDoc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.rubric')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course')),
                ('numberGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupco')),
                ('studentCOEV1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.student')),
                ('studentCOEV2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.coevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=60)),
                ('actions', models.CharField(max_length=60)),
                ('metodology', models.CharField(max_length=60)),
                ('courses', models.CharField(max_length=60)),
                ('progress', models.CharField(max_length=60)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.educationresult')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementEduResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureERPeriod', models.CharField(max_length=60)),
                ('experts', models.IntegerField()),
                ('competents', models.IntegerField()),
                ('apprentices', models.IntegerField()),
                ('beginners', models.IntegerField()),
                ('codeResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.educationresult')),
                ('codeRubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planPeriod', models.CharField(max_length=60)),
                ('diagnosis', models.CharField(max_length=60)),
                ('analysis', models.CharField(max_length=60)),
                ('codeResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.educationresult')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHomework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.assignment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course')),
                ('numGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupco')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course')),
                ('numGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupco')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='coevaluation',
            name='codeRubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.rubric'),
        ),
        migrations.AddField(
            model_name='coevaluation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course'),
        ),
        migrations.AddField(
            model_name='coevaluation',
            name='numberGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupco'),
        ),
        migrations.AddField(
            model_name='coevaluation',
            name='studentCOEV2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.student'),
        ),
        migrations.CreateModel(
            name='AutoEvaluationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoPeriod', models.CharField(max_length=60)),
                ('numberStudents', models.IntegerField()),
                ('codeCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course')),
                ('codeRubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.rubric')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='codeResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.educationresult'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='numGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupco'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.student'),
        ),
    ]
