# Generated by Django 3.2.3 on 2021-06-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAssignment', models.BigIntegerField()),
                ('idDocument', models.BigIntegerField()),
                ('nameAssignament', models.CharField(max_length=60)),
                ('numGroup', models.BigIntegerField()),
                ('course', models.BigIntegerField()),
                ('codeResult', models.IntegerField()),
                ('dateAssignment', models.DateTimeField()),
                ('dateLimitAssignment', models.DateTimeField()),
                ('description', models.CharField(max_length=60)),
                ('format', models.CharField(max_length=60)),
                ('delivery', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AutoEvaluationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCourse', models.BigIntegerField()),
                ('codeRubric', models.BigIntegerField()),
                ('autoPeriod', models.CharField(max_length=60)),
                ('idDocument', models.CharField(max_length=60)),
                ('numberStudents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRubric', models.BigIntegerField()),
                ('studentCOEV', models.BigIntegerField()),
                ('numberGroup', models.BigIntegerField()),
                ('course', models.BigIntegerField()),
                ('documentAttached', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCourse', models.BigIntegerField(default=1)),
                ('periodPlan', models.CharField(default='Test', max_length=60)),
                ('referencePlan', models.IntegerField(default=1)),
                ('nameCourse', models.CharField(default='Test', max_length=60)),
                ('departmentCourse', models.CharField(default=1, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EducationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeResult', models.IntegerField()),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numGroup', models.BigIntegerField()),
                ('course', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDocument', models.CharField(max_length=60)),
                ('numGroup', models.BigIntegerField()),
                ('course', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDocument', models.CharField(max_length=60)),
                ('idHomework', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planPeriod', models.CharField(max_length=60)),
                ('codeResult', models.IntegerField()),
                ('idDocument', models.BigIntegerField()),
                ('diagnosis', models.CharField(max_length=60)),
                ('analysis', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementEduResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureERPeriod', models.CharField(max_length=60)),
                ('codeRubric', models.BigIntegerField()),
                ('codeResult', models.IntegerField()),
                ('experts', models.IntegerField()),
                ('competents', models.IntegerField()),
                ('apprentices', models.IntegerField()),
                ('beginners', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=60)),
                ('reference', models.IntegerField()),
                ('idPerson', models.CharField(max_length=60)),
                ('actions', models.CharField(max_length=60)),
                ('metodology', models.CharField(max_length=60)),
                ('courses', models.CharField(max_length=60)),
                ('progress', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPerson', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRubric', models.BigIntegerField()),
                ('rubric', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentCOEV1', models.BigIntegerField()),
                ('studentCOEV2', models.BigIntegerField()),
                ('numberGroup', models.BigIntegerField()),
                ('course', models.BigIntegerField()),
                ('codeRubric', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aesci_api.person')),
                ('charge', models.CharField(max_length=60)),
            ],
            bases=('aesci_api.person',),
        ),
        migrations.CreateModel(
            name='PairEvaluator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aesci_api.person')),
                ('institution', models.CharField(max_length=60)),
            ],
            bases=('aesci_api.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aesci_api.person')),
                ('carrer', models.CharField(max_length=60)),
            ],
            bases=('aesci_api.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aesci_api.person')),
                ('departmentDoc', models.CharField(max_length=60)),
            ],
            bases=('aesci_api.person',),
        ),
    ]
