# Generated by Django 3.2.3 on 2021-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='rubric',
            field=models.CharField(max_length=255),
        ),
    ]
