# Generated by Django 3.2.8 on 2022-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
