# Generated by Django 3.2.8 on 2022-01-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='username',
            new_name='usernameTeacher',
        ),
    ]
