# Generated by Django 4.0.2 on 2022-03-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorassignment',
            old_name='id',
            new_name='id',
        ),        
    ]
