# Generated by Django 3.2.5 on 2021-07-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='format',
            new_name='formate',
        ),
    ]
