# Generated by Django 3.2.5 on 2021-10-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0002_auto_20211004_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='referencePlan',
        ),
    ]
