# Generated by Django 3.2.3 on 2021-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0002_alter_rubric_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='rubric',
            field=models.JSONField(),
        ),
    ]
