# Generated by Django 3.2.8 on 2022-03-16 22:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0002_rename_idindicatorassignment_indicatorassignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='isActive',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='evaluationassignment',
            name='evaluationType',
            field=models.CharField(choices=[('AUTO', 'Autoevaluation'), ('COTE', 'Coevaluation teacher'), ('COST', 'Coevaluation student'), ('EVAL', 'Evaluation teacher')], max_length=4),
        ),
    ]
