# Generated by Django 3.2.5 on 2021-09-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0002_rename_codeia_indicatorassignment_codepi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='idPerson',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='homeworkgroupstudent',
            old_name='idGroupStudent',
            new_name='GroupStudent',
        ),
        migrations.RenameField(
            model_name='homeworkgroupstudent',
            old_name='idHomework',
            new_name='Homework',
        ),
        migrations.RenameField(
            model_name='indicatorassignment',
            old_name='idHomework',
            new_name='Homework',
        ),
        migrations.RenameField(
            model_name='indicatorassignment',
            old_name='codePI',
            new_name='codePzI',
        ),
        migrations.RenameField(
            model_name='pairevaluator',
            old_name='idPerson',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='idPerson',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='idPerson',
            new_name='Person',
        ),
    ]
