# Generated by Django 3.2.5 on 2021-07-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0002_rename_format_assignment_formate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='formate',
            new_name='formatAssignment',
        ),
    ]
