# Generated by Django 3.2.5 on 2021-08-02 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0003_rename_formate_assignment_formatassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dateAssignment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dateLimitAssignment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='idAssignment',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
