# Generated by Django 3.2.5 on 2021-10-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0003_remove_course_referenceplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Person',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='pairevaluator',
            old_name='Person',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Person',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Person',
            new_name='role',
        ),
    ]
