# Generated by Django 3.2.5 on 2021-09-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0003_auto_20210907_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorAssignment',
        ),
    ]
