# Generated by Django 3.2.8 on 2022-01-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0003_auto_20211202_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorassignment',
            old_name='homework',
            new_name='assignment',
        ),
    ]
