# Generated by Django 3.2.8 on 2022-03-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0003_auto_20220316_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoutcome',
            name='isActive',
            field=models.CharField(default='', max_length=60),
        ),
    ]
