# Generated by Django 3.2.5 on 2021-08-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0004_auto_20210802_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.teacher'),
        ),
    ]
