# Generated by Django 3.2.5 on 2021-09-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0004_delete_indicatorassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numGroupsou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupco')),
                ('performanceIndicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.performanceindicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.homeworkgroupstudent')),
                ('indicatorGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.indicatorgroup')),
            ],
        ),
    ]
