# Generated by Django 3.2.5 on 2021-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0004_auto_20211005_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('PairEvaluator', 'Pair Evaluator'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=60),
        ),
        migrations.AlterField(
            model_name='pairevaluator',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('PairEvaluator', 'Pair Evaluator'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('PairEvaluator', 'Pair Evaluator'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('PairEvaluator', 'Pair Evaluator'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=60),
        ),
    ]
