# Generated by Django 3.2.8 on 2022-01-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0004_rename_homework_indicatorassignment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.assignment'),
        ),
    ]
