# Generated by Django 4.0.2 on 2022-04-08 23:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0004_studentoutcome_isactive'),
    ]

    operations = [        
        migrations.AddField(
            model_name='performanceindicator',
            name='isActive',
            field=models.CharField(default='', max_length=60),
        ),        
    ]
