# Generated by Django 3.2.5 on 2021-10-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0005_auto_20211005_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='pairevaluator',
            name='role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
    ]
