# Generated by Django 3.2.5 on 2021-08-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0005_alter_assignment_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkGroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupstudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groupteacher',
            name='course',
        ),
        migrations.DeleteModel(
            name='HomeworkStudent',
        ),
        migrations.AddField(
            model_name='homeworkgroupstudent',
            name='idGroupStudent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupstudent'),
        ),
        migrations.AddField(
            model_name='homeworkgroupstudent',
            name='idHomework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.assignment'),
        ),
    ]
