# Generated by Django 4.0.2 on 2022-04-13 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0005_remove_assignment_idassignment_assignment_id_and_more'),
    ]

    operations = [        
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='documentType',
            field=models.CharField(default='null', max_length=60),
            preserve_default=False,
        ),    		
    ]
