# Generated by Django 3.2.8 on 2022-01-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0006_rename_idassignment_assignment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='id',
            new_name='idAssignment',
        ),
    ]
