# Generated by Django 3.2.5 on 2021-08-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0006_auto_20210803_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='formatAssignment',
        ),
        migrations.AddField(
            model_name='homeworkgroupstudent',
            name='deliveryURL',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='homeworkgroupstudent',
            name='grade',
            field=models.FloatField(default=None),
        ),
    ]
