# Generated by Django 4.0.2 on 2022-04-20 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0006_remove_assignment_idassignment_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatormeasure',
            name='levelMeasure',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
