# Generated by Django 3.2.5 on 2021-10-08 22:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0006_auto_20211005_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=None, null=True)),
                ('link', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=8), null=True, size=8)),
                ('Assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.assignment')),
                ('GroupStudent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupstudent')),
            ],
        ),
        migrations.AlterField(
            model_name='indicatorassignment',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.assignmentstudent'),
        ),
        migrations.DeleteModel(
            name='HomeworkGroupStudent',
        ),
    ]
