# Generated by Django 3.2.5 on 2021-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0007_indicatormeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatormeasure',
            name='codeMeasure',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Apprentice'), ('3', 'Competent'), ('4', 'Expert')], max_length=1),
        ),
    ]
