# Generated by Django 3.2.5 on 2021-10-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0007_auto_20211008_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='nameAssignament',
            new_name='nameAssignment',
        ),
    ]
