# Generated by Django 3.2.8 on 2022-04-28 17:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0007_remove_assignment_idassignment_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=100),
        ),
    ]
