# Generated by Django 3.2.5 on 2021-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0007_auto_20210811_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkgroupstudent',
            name='deliveryURL',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkgroupstudent',
            name='grade',
            field=models.FloatField(default=None, null=True),
        ),
    ]
