# Generated by Django 3.2.5 on 2021-10-10 04:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0008_rename_nameassignament_assignment_nameassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentstudent',
            name='link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), null=True, size=8),
        ),
    ]
