# Generated by Django 3.2.8 on 2022-05-14 16:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0008_alterDocumentTypeToCharField'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentoutcome',
            name='codeRubric',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='assignmentstudent',
            name='link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RubricStudentOutcome',
            fields=[
                ('idRubricStudentOutcome', models.AutoField(primary_key=True, serialize=False)),
                ('codeRubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.rubric')),
                ('codeStudentOutcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.studentoutcome')),
            ],
        ),
    ]
