# Generated by Django 3.2.5 on 2021-09-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0008_alter_indicatormeasure_codemeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementeduresult',
            name='codeRubric',
        ),
        migrations.RemoveField(
            model_name='measurementeduresult',
            name='measureERPeriod',
        ),
        migrations.DeleteModel(
            name='IndicatorAssignment',
        ),
    ]
