# Generated by Django 3.2.8 on 2022-05-12 04:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0009_createUndergraduateProgram'),
    ]

    operations = [
        migrations.AddField(
            model_name='undergraduateprogram',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RenameModel('undergraduateprogram', 'program'),
    ]
