# Generated by Django 3.2.5 on 2021-09-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0009_auto_20210910_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeMeasure', models.CharField(choices=[('1', 'Beginner'), ('2', 'Apprentice'), ('3', 'Competent'), ('4', 'Expert')], max_length=1)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.homeworkgroupstudent')),
                ('indicatorGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.indicatorgroup')),
            ],
        ),
    ]
