# Generated by Django 3.2.5 on 2021-09-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0010_indicatorassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorgroup',
            old_name='numGroupsou',
            new_name='numGroup',
        ),
    ]
