# Generated by Django 3.2.8 on 2022-07-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0010_createUndergraduateProgram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstudent',
            old_name='id',
            new_name='idGroupStudent',
        ),
        migrations.RenameField(
            model_name='groupteacher',
            old_name='id',
            new_name='idGroupTeacher',
        ),
        migrations.AddField(
            model_name='evaluationassignment',
            name='studentEvaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupstudent'),
        ),
        migrations.AddField(
            model_name='evaluationassignment',
            name='teacherEvaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aesci_api.groupteacher'),
        ),
    ]
