# Generated by Django 3.2.8 on 2022-05-12 04:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0010_renameUndergraduateProgramToProgram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='idUndergraduateProgram',
            new_name='idProgram',
        ),
    ]
