# Generated by Django 3.2.8 on 2021-10-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0011_auto_20211022_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationResult',
        ),
    ]
