# Generated by Django 3.2.5 on 2021-09-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0011_rename_numgroupsou_indicatorgroup_numgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementEduResult',
        ),
    ]
