# Generated by Django 3.2.5 on 2021-09-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0012_delete_measurementeduresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorassignment',
            name='codeMeasure',
        ),
        migrations.CreateModel(
            name='EvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluationType', models.CharField(choices=[('AUTO', 'Autoevaluation'), ('COTE', 'Coevaluation teacher'), ('COST', 'Coevaluation student')], max_length=4)),
                ('codeMeasure', models.CharField(choices=[('1', 'Beginner'), ('2', 'Apprentice'), ('3', 'Competent'), ('4', 'Expert')], max_length=1)),
                ('indicatorAssignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesci_api.indicatorassignment')),
            ],
        ),
    ]
