# Generated by Django 3.2.8 on 2021-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0012_delete_educationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationassignment',
            name='documentAttached',
            field=models.CharField(max_length=200),
        ),
    ]
