# Generated by Django 3.2.5 on 2021-09-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0013_auto_20210913_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationAssignment',
        ),
    ]
