# Generated by Django 3.2.8 on 2021-10-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0013_alter_evaluationassignment_documentattached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationassignment',
            name='documentAttached',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
