# Generated by Django 3.2.5 on 2021-09-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0015_evaluationassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationAssignment',
        ),
    ]
