# Generated by Django 3.2.5 on 2021-09-13 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesci_api', '0017_auto_20210913_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationassignment',
            name='documentAttached',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='homeworkgroupstudent',
            name='link',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=8), null=True, size=8),
        ),
    ]
